#+setupfile: ~/blog/lvl-2.org
#+title: Losing weight by eating right
#+date: <2014-02-17>

Losing weight is one of my new year [[file:resolutions.org][resolutions]]. I started on a
"reduced gluten" diet around 10th of January. My main motivation for
this particular diet was in solidarity with my wife. She's suspecting
that gluten intolerance has an adverse effect on her health and wanted
to verify this by elimination. Not sure what I expected, but the
benefits I've had so far have exceeded them.

Almost immediately after cutting out grains (all possible sources of
gluten we could think of) we started feeling improvements. We ate less,
but didn't feel hungry; we didn't get cravings for snack throughout the
day, or in the middle of the night. I was used to being ravenous by
noon, but this too disappeared and I started lunching later. My (bad)
habit of adding extra sugar in my tea or coffee also disappeared: I
simply didn't feel a need for it any more. I arrived home and was able
to hold a coherent conversation rather than diving into the fridge to
sate my hunger.

Not being hungry so much was far from the only benefit. Both my wife and
I felt like we had more energy. And rather than feeling a "slump" after
a meal we maintained a pretty good level of energy. We did notice that
if we indulged on cake, or toast, we would soon after get slumps of low
energy---and in some cases stomach pains. My wife, in particular, also
felt that she has been sleeping better---and not waking up ravenous in
the middle of the night.

I'm not giving you my exact measureents, but two weeks in I had lost one
cm around each overarm, one cm around each thigh, and two cm around my
belly. That is pretty decent while pretty much eating whatever I want
to, and doing no exercise. (I'm not proud of that last bit, it's just a
fact of life.) Now at four weeks in I've lost another two cm around my
belly, and my trousers are starting to feel loose.

It's not been hard to stick to this diet for the most part. In some ways
I think I'm eating better than before: I just cut out the fillers. I
don't actually end up eating much more of the rest. (This is great as I
did initially think it would be a fearsomely expensive diet.) Although
the title of this post contains "losing weight" I still haven't got a
set of scales, so I don't know how well I'm doing on my goal of going
below 75kg by end of April on this diet. But I feel better and I enjoy
the food---so I think I'm sticking with it.
