#+title: Resolutions Progress
#+date: <2014-06-25>
#+index: Resolutions!2014 Progress

Thought I'd post a quick note on progress with on my [[file:resolutions.org][New Years
Resolutions]].

I most likely didn't manage to get down to 75kg by end of April.
However, I did get to 75.9kg at the end of May, which makes my BMI just
about 24, and as far as I know /I am still losing weight/. Crucially,
this is without a massive work-out regimen, just by /sustainable/ change
in diet. (As far as I know.) And it is an enjoyable one too :-)

I have signed up as a STEM Ambassador, but due to work commitments I
have not yet managed to start a Code Club. I am waiting for official OK
from work (because I have to do it during work hours) before I start.

I have not managed to write as much as I had hoped. 5 published posts
on this blog, and a draft in the works, plus a couple posts on our
[[http://techblog.net-a-porter.com/author/stig/][company tech blog]]. Well, what do you know. That was actually a bit
more than I thought :-)

On the "meeting up with friends" front I started off well, but have the
last month or two have been not quite so successful.

Conclusion: Need to do better.
