#+title: Resolutions
#+date: 2014-01-01
#+index: Resolutions!2014

The Brautasets stayed in London again this year. We do not like to
travel at the best of times, and doing eight-hour journeys at Christmas
with a two-year-old is not our idea of fun. I've had Christmas off
though and we stocked the larder in advance. In other words: good food
and quality family time was had. I've also had a little time to think of
resolutions for 2014.

There's not much point to resolutions unless they're quantifiable.
Otherwise, how would your friends hold you accountable? (And make fun of
you if you fail?) So rather than "drink more" "exercise less" I've tried
to only pick resolutions that can be measured or externally verified.

I've been wanting to do contribute more to my local community for some
time. In particular I've been after something where I can contribute
with my experience. [[https://www.codeclub.org.uk][CodeClub]], teaching
programming to school-children aged 9--11, has caught my eye. The
curriculum is provided for you so all you have to do is contribute one
hour a week to run a class. Conveniently you can run it at a school or
social club near you. Check them out if you find this interesting!

On the personal front I plan to lose a little weight. I think I am about
80 kg right now, which makes my BMI a little above 25---meaning I'm
/technically/ overweight. I want to get down to 75 which will make my
BMI just under 24. I'll give myself until my birthday (late April), and
I want to keep that weight for the rest of the year. I'm not sure how to
make this happen but I figure more exercise, more fruit and veg, and
less carbohydrates will play a part. At the moment I don't do any
exercise at all so that part shouldn't be too hard.

I also want to write more this year. Last year I managed 11 posts on
this blog. (Not counting a couple still in draft stage.) I also managed
three posts on my
[[http://techblog.net-a-porter.com/author/stig/][work's tech blog]]. I
will consider this the 'low water mark' for this year, so this year I
will commit to write at least 15 posts. The distribution of posts across
various blogs is not important, as the point is to improve my writing.

Last but not least: I want to make a concerned effort to see my friends
more often. I've been back in London for nearly 2 years and I believe I
can count the number of times I've managed to go out and meet old
friends /on the fingers of one hand/. Consequently, this year I hope to
meet friends for a night out at least once a month: 12 times. How hard
can it be?
