#+setupfile: ~/blog/lvl-2.org
#+title: Blade 2
#+date: <2002-04-05>
#+category: Reviews

Went to Harrow to watch Blade2 with GF. It was OK, but I was a bit
disappointed with the inconsistency with the first Blade movie.

Blade himself was just too hard, too cool, too strong and too fast to be
even remotely likable, but I was especially disappointed that the
vampires in Blade 2 could not stand sunshine even through armoured
gloves, considering Deacon Frost and his gang could stand the sun's rays
by just putting sunblock on naked skin in the first Blade movie. That's
just PATHETIC. And, I almost forgot, I had hoped for the red-haired
vamp-girl (Verlaine, played by Marit Velle Kile) to kick some serious
butt. That's probably just a selfish wish tho, based on 'Oh, I went to
school with her!' ;D

Some of the fighting scenes, as were the 'swing between poles in the
roof'-scene in the opening, were very artificial and blatantly animated.
And one more thing seemed strange; a stake through the heart could kill
the vampires (and the Reapers), meaning that they'd die without a
working blood flow, yet half of Priest's (or so I think it was, anyway)
head continued to live after it was chopped off--where's the blood
pumping in that body part?
