#+setupfile: ~/blog/lvl-2.org
#+title: Heinlein's list of skills
#+date: <2002-09-11>

Today, in addition to getting my first ever 'get well soon' card, I sat
down to see how manly I am, according to Robert Heinlein. Here's
Heinlein's list of skills:

#+BEGIN_QUOTE
  A Man should be able to change a diaper, plan an invasion, butcher a
  hog, conn a ship, design a building, write a sonnet, balance accounts,
  build a wall, set a bone, comfort the dying, take orders, give orders,
  cooperate, act alone, solve equations, analyze a new problem, pitch
  manure, program a computer, cook a tasty meal, fight efficiently and
  die gallantly. Specialization is for insects.
#+END_QUOTE

Let's break it down and see how I compare:

1.  Change a diaper: Ah, yes. This I should be able to do.
2.  Plan an invasion: No, I'm not a strategist.
3.  Butcher a hog: Kill a hog, probably. Butcher it? Probably not.
4.  Conn a ship: Not a ship, but a boat, yes.
5.  Design a building: No.
6.  Write a sonnet: No.
7.  Balance accounts: Unfortunately, no. Not my accounts anyway.
8.  Build a wall: Yes.
9.  Set a bone: I should think so.
10. Comfort the dying: Alas, I would probably be at loss here.
11. Take orders: Yes, grudgingly.
12. Give orders: Yes, unwillingly.
13. Cooperate: Yes.
14. Act alone: Yes.
15. Solve equations: Yes.
16. Analyze a new problem: Yes.
17. Pitch manure: Ugh. If I had too...
18. Program a computer: Yes, most willingly :D
19. Cook a tasty meal: Occasionally.
20. Fight efficiently and die gallantly: Fight efficiently, maybe. Die
    gallantly, probably not.

Also on the list of things to do today were finishing up the
moving-business. I hate moving. I have too much stuff. I have to get rid
of some of this junk, either by sending it off to Norway or to the tip.
I realise that I'm having problems throwing away stuff. However, I'm
finished now. At least it's all in my new room. I now have to find a way
to stash all this junk (the part I'm going to keep of it anyway).

Watched Star Trek.
