#+title: About Stig Brautaset

I live and work remotely from rural [[https://en.wikipedia.org/wiki/Berwick-upon-Tweed][Berwick-upon-Tweed]] in the North
East of England. I've previously lived in London (about 14 years) and
Hong Kong (1 year). Employers have paid me to write HTML, PHP, Perl,
C, JavaScript, Java, Objective-C, Scala, Python, Bash and English.

I am from Hovdebygda, a village in [[https://en.wikipedia.org/wiki/%C3%98rsta][Ørsta Municipality]] on the west
coast of Norway. I studied electronics, and endured compulsory
military service as a sonar operator on a submarine, before moving to
London for university. I studied AI at the University of Westminster,
graduating in 2003.

I started writing the popular [[https://github.com/stig/json-framework/][SBJson]] JSON parser/generator for
Objective-C in 2007, and have maintained it ever since. It's now in
its 5th major version and have over 3800 stars on GitHub.

* About this website

  I currently build this website in Emacs with Org mode, and use Org's
  "publish" feature to generate static HTML files that I deploy on
  Amazon S3 behind a CloudFront distribution and a free SSL
  certificate.
