#+title: About Stig Brautaset

I studied AI at the University of Westminster, where I graduated
in 2003. Since then I've worked in software development in industries
such as fashion, investment banking, online photos, and fintech.
Employers have paid me to write HTML, PHP, Perl, C, JavaScript, Java,
Objective-C, Scala, Python, Bash and English.

I wrote the first version of the (moderately popular) [[https://github.com/stig/json-framework/][SBJson]] JSON
parser/generator for Objective-C in 2007, and have maintained it ever
since. It's now in its 5th major version and have over 3800 stars on
GitHub.

I grew up in Hovdebygda, a village in [[https://en.wikipedia.org/wiki/%C3%98rsta][Ørsta Municipality]] on the west
coast of Norway. I studied audio/video electronics, then endured
compulsory military service as a sonar operator on a submarine.  I
then went to University in London.  15 years later I'd had enough of
the Big Smoke and moved to rural [[https://en.wikipedia.org/wiki/Berwick-upon-Tweed][Berwick-upon-Tweed]].

If you want more details, I suggest reading the transcript of my
[[file:articles/2016/berwick-academy-stem-talk.org][Berwick Academy STEM Talk]] where I talked for 45 minutes about my
education and career.

* Contact
  :PROPERTIES:
  :CUSTOM_ID: contact
  :END:

If you want to contact me about one of my many software projects I ask
that you do so via its [[https://github.com/stig][GitHub]] page.

Otherwise the best way of contacting me---unless you have my mobile
phone number---is via email: [[mailto:stig@brautaset.org][stig@brautaset.org]].

If you don't like email & don't mind waiting a while for a response
you can alternatively try [[http://twitter.com/stigbra][Twitter]]. (I check Twitter roughly once a
week.)
