#+setupfile: lvl-0.org
#+title: About Stig Brautaset

I am an experienced software engineer based in the North East of
England. I currently work (remotely) for CircleCI.

I'm originally from [[https://en.wikipedia.org/wiki/%C3%98rsta][Ørsta]], on the west coast of Norway.  I studied
electronics, and served as a sonar operator on a submarine during
compulsory military service, before moving to London to study AI at
the University of Westminster.  I graduated in 2003.

* About SBJson

  I started writing the popular [[https://github.com/stig/json-framework/][SBJson]] JSON parser/generator for
  Objective-C in 2007, and have maintained it ever since. It's now in
  its 5th major version and have over 3800 stars on GitHub.

* About this website

  I build this website in Emacs' Org mode, which can publish static
  HTML files. Those I deploy on Amazon S3 behind a CloudFront
  distribution and a free SSL certificate.

  Code examples are by me, unless otherwise specified, and available
  under the [[https://creativecommons.org/licenses/by-sa/4.0/][Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)]]
  lisence.

* Contact
  :PROPERTIES:
  :CUSTOM_ID: contact
  :END:

  If you want to contact me about one of my software projects I ask
  that you do so by filing an issue on [[https://github.com/stig][GitHub]].

  Otherwise the best way of contacting me is via email. I used to give
  my email address here, but in a (most likely futile) attempt to
  limit spam I've removed it. Don't worry: I'm sure you'll be able to
  figure it out.
