#+title: About Stig Brautaset

I grew up in Hovdebygda, a village in [[https://en.wikipedia.org/wiki/%C3%98rsta][Ørsta Municipality]] on the west
coast of Norway.  At 16 I started studying electronics for 4 years,
then endured compulsory military service as a sonar operator on a
submarine.  Then I went off to London where I studied AI at the
University of Westminster, and graduated in 2003.

I stayed in London (interrupted by one year in Hong Kong) for 12 years
after graduating, doing software development in fintech, online
photos, investment banking, and fashion.  Employers have paid me to
write HTML, PHP, Perl, C, JavaScript, Java, Objective-C, Scala,
Python, Bash and English.

I started writing the moderately popular [[https://github.com/stig/json-framework/][SBJson]] JSON parser/generator
for Objective-C in 2007, and have maintained it ever since. It's now
in its 5th major version and have over 3800 stars on GitHub.

In 2015 my little family had had enough of the Big Smoke and we upped
sticks & moved to rural [[https://en.wikipedia.org/wiki/Berwick-upon-Tweed][Berwick-upon-Tweed]].

If you want more details, I suggest reading the transcript of my
[[file:articles/2016/berwick-academy-stem-talk.org][Berwick Academy STEM Talk]] where I talked for 45 minutes about my
education and career.

* About this website

  I currently build this website in Emacs with Org mode, and use Org's
  "publish" feature to generate static HTML files that I deploy on
  Amazon S3 behind a CloudFront distribution and a free SSL
  certificate.
