#+title: Publications

This is a list of some of my talks & articles hosted elsewhere:

- [[http://techblog.net-a-porter.com/author/stig/][My Net-a-Porter Techblog entries (2013--2014)]]

  I wrote a few entries on the Net-a-Porter tech blog in my various
  roles there. (Details about my roles on my linkedin profile.)

- [[https://vimeo.com/86478323][Delighting your users with SBJson 4 (2013)]]

  This is my first _Pecha Kucha_ style talk, made at NSLondon meetup.
  The sound is not great, and one of my slides is a bit misleading,
  but I have a special fondness for this one as it's the first time
  I've been invited to speak.

- [[http://skillsmatter.com/podcast/scala/overcoming-u-turns-and-dead-ends-lessons-of-using-scala-akka-spray-on-heroku][Overcoming U-turns and Dead Ends: Lessons of using Scala, Akka & Spray on Heroku (2013)]]

  I presented this "experience talk" at Scala eXchange 2013 with Sam
  Dean. (I'm afraid you have to log in to view the video.) It's a
  mish-mash of stuff we learnt while building the backend of The
  Netbook---Net-A-Porter's social network offering.

- [[http://www.onlamp.com/pub/a/onlamp/2006/01/19/libtap.html?CMP=OTC-6YE827253101&ATT=Testing+C+with+Libtap][Testing C with Libtap (2006)]]

  I talked at YAPC::NA 2005 (I believe) on this topic and was
  approached by a member of the audience to write it up as an article
  for ONLamp magazine. This is the result.

- [[file:files/m4.pdf][Creating HTML with M4 (2002)]]

  A long, long time ago I used =make= and =cpp= to maintain my website.
  Later I upgraded to =m4=. I ended up writing an article on the
  subject, and this was published in Linux Magazine.
