#+title: My Preferred CSS
#+PROPERTY: header-args:css :tangle style.css :results silent

CSS styles for my blog. I tangle this file to =style.css=. I try to
exercise all the styles in [[file:content/style-demo.org][style-demo]].

* Define CSS variables for Colours

Currently I like ~orange~ and ~blanchedalmond~, so those colours
feature heavily. Hope I'm not overdoing it!

#+begin_src css
:root {
    --accent: darkorange;
    --alt-accent: blanchedalmond;
    --background: white;
    --footnotes: gray;
    --highlight: gold;
    --text: black;
}
#+end_src

* Set the Scene

Fonts, navigation, and colourful header and footer.

#+begin_src css
html {font-family: Optima, -apple-system, sans-serif}

h1, h2, h3, h4, h5, h6 {color: var(--accent)}

#preamble, #content, #postamble {
    padding: 0.5ch;
}

#preamble, #postamble {
    background-color: var(--alt-accent);
    border-radius: 1px;
}

#preamble {border-bottom: 3px solid var(--accent)}
#postamble {border-top: 3px solid var(--accent)}

header, footer {
    display: flex;
    flex-wrap: wrap;
}

.header-title > a:link, a:visited {text-decoration: none}

.header-title {flex: 80%}
.header-nav {flex: 20%}
.footer-date {flex: 30%}
.footer-copyright {}

@media (max-width: 600px) {
    .header-title,
    .header-nav,
    .footer-date,
    .footer-copyright {flex: 100%}

    nav > ul {
	list-style: none;
	display: flex;
	width: 100%;
	padding: 0;
	margin: 0;
    }

    nav > ul > li + li:before {
	content: "•";
	padding: 0 0.5em;
	color: var(--accent);
    }
}
#+end_src

* Drawers

These are blocks that show up a bit differently. I use them for
jumping out of the text a bit, for example to mark a post as outdated,
cf [[file:content/posts/leafnode-nntp-os-x.org
][my leafnode post]].

#+begin_src css
.drawer {
    border: 3px dashed var(--accent);
    background-color: var(--alt-accent);
    margin: 1em;
    padding: 0.5em;
}
.drawer h6 {margin: 0}
#+end_src
* Links

#+begin_src css
a:link {color: var(--accent)}
a:active {color: var(--alt-accent)}
a:visited {
    color: var(--text);
    background-color: transparent;
}
a:hover {
    color: var(--text);
    background-color: var(--highlight);
}
#+end_src

* Tables

Most of this is straight out of Org's default CSS, but I like me some
borders!

#+begin_src css
table, thead, tbody {border: 1px solid var(--accent)}
thead {background-color: var(--alt-accent)}
th, td {padding: 0em 0.5em}
tr:nth-child(even){background-color: var(--alt-accent)}
#+end_src

* Tags

My index page has tags to classify posts. This makes them look snazzy,
I think. [[https://gongzhitaao.org/orgcss/][Credit]].

#+begin_src css
.tag {
    float: right;
    background-clip: padding-box;
    font-family: monospace;
    padding: 0;
    font-size: 80%;
    font-weight: normal;
    background-color: var(--background);
}

.tag span {
    background-color: var(--alt-accent);
    border-top: 1px solid var(--accent);
    border-bottom: 1px solid var(--accent);
    border-radius: 1px;
    color: var(--text);
    line-height: 1;
    margin-left: .3em;
    padding: .3em;
}
#+end_src

* Footnotes in HTML

These get a diminutive orange ~<hr/>~ above, and have slightly lighter
font colour to make them stand out less.

#+begin_src css
.footpara {display: inline}
.footdef {margin-bottom: 1em}

#footnotes {
    color: var(--footnotes);
    font-size: smaller;
}

#footnotes hr {
    border: 0;
    border-top: 1px solid var(--accent);
    border-radius: 1px;
    width: 50%;
}
#+end_src

* Images

Scale images down if they're wider than the text.

#+begin_src css
img {max-width: 95%}
#+end_src

* Checkboxes

#+begin_src css
.off > code { font-family: monospace; color: red; }
.on > code { font-family: monospace; color: green; }
.trans > code { font-family: monospace; color: orange; }
#+end_src

* Styling source code

With ~(setq org-html-htmlize-output-type "css")~ Org will publish
source code markup with semantic CSS selectors rather than inline CSS.
This allows us to get nice-looking output even when Emacs is
publishing in ~--batch~ mode.

#+begin_src css
.org-builtin {color: #483d8b}
.org-clojure-keyword {color: #008b8b}
.org-comment {color: #b22222}
.org-comment-delimiter {color: #b22222}
.org-doc {color: #8b2252}
.org-function-name {color: #0000ff}
.org-keyword {color: #a020f0}
.org-string {color: #8b2252}
.org-type {color: #228b22}
.org-variable-name {color: #a0522d}
#+end_src

When asking Org to number source code examples it uses these classes.

#+begin_src css
.linenr {font-size: smaller}
.code-highlighted {background-color: var(--highlight)}
#+end_src

Let's also outline our code blocks with our favourite colour:

#+begin_src css
pre {
    border: 1px solid var(--accent);
    box-shadow: 3px 3px 3px var(--alt-accent);
}

pre.src:before {
    background-color: var(--alt-accent);
    border: 1px solid var(--accent);
}

pre.src-json:before {content: 'JSON'}
#+end_src

* Cater for bigger screens

I target small screens by default, but here I make allowances for
larger screens.

Increase the body's font size, and limit its width. Center the body by
automatically adjusting margins surrounding it.

Introduce small margin & padding around figures, which looks a bit
nicer on big screens. Particularly when used in a columnar layout,
which we also activate here.

#+begin_src css
@media (min-width: 600px) {
    html {font-size: x-large}

    body {
        max-width: 65ch;
        margin: auto;
    }

    figure {
        margin: 1ch;
        padding: 1ch;
    }

    .row {display: flex}
    .column {flex: 50%}
}
#+end_src
