* A
  - Akka
    - [[file:articles/2013/injecting-akka-testprobe.org][Injecting TestProbe in place of children in Scala]]
    - [[file:articles/2013/scalatest-with-akka.org][Working with ScalaTest]]
  - [[file:articles/2008/avenue-que.org][Avenue Que]]
* B
  - Banking
    - [[file:articles/2004/chip-and-pin.org][Chip and Pin]]
    - [[file:articles/2004/banking-trouble.org][Co-operative Trouble]]
  - Bar Charts
    - [[file:articles/2006/generating-bar-charts-with-sql.org][Generating with SQL]]
  - [[file:articles/2014/good-ideas.org][Basic Income]]
  - [[file:articles/2002/blade-2.org][Blade 2]]
  - [[file:articles/2005/blade-trinity.org][Blade Trinity]]
  - Bread and "butter" pudding
    - [[file:articles/2013/dairy-free-bread-pudding.org][A dairy-free recipe]]
* C
  - Cache
    - [[file:articles/2014/optimising-http-cache-hit-rate.org][Maximising Hit Rates]]
  - Clojure
    - [[file:articles/2015/response-to-haskell-lisp-philosophical-differences.org][On this Lisp's non-difference from Haskell]]
    - [[file:articles/2017/n-queens.org][Solving the N Queens problem]]
    - [[file:articles/2014/learning-clojure.org][Using it to solve Euler Problems]]
* D
  - [[file:articles/2005/untraditional-refactoring-technique.org][Dead code elimination]]
  - Development
    - [[file:articles/2015/benchmarking.org][A lesson in Benchmarking]]
* E
  - Education
    - [[file:articles/2014/good-ideas.org][Why it should be free or at least affordable]]
  - [[file:articles/2017/electoral-reform-now.org][Electoral Reform]]
  - Emacs Theme
    - [[file:articles/2017/hydra-theme-switcher.org][Switching with Hydra]]
  - [[file:articles/2004/extreme-programming-explained.org][Extreme Programming Explained]]
* F
  - First Past the Post
    - [[file:articles/2017/electoral-reform-now.org][Voting system]]
  - FizzBuzz
    - [[file:articles/2016/fizzbuzz.org][A Tweetable solution using sed and xargs]]
* G
  - [[file:articles/2007/game-tree-search.org][Game-tree search]]
  - [[file:articles/2006/playing-at-the-edge-of-ai.org][Genetic Algorithms]]
* H
  - Hydra
    - [[file:articles/2017/hydra-theme-switcher.org][Writing an Emacs Theme Switcher]]
* I
  - ISA
    - [[file:articles/2017/open-letter-to-anne-marie-mp.org][Tories' benefit to those on higher income]]
* J
  - Jekyll
    - [[file:articles/2016/how-i-blog-this-week.org][Using with Org mode]]
* L
  - Leafnode
    - [[file:articles/2016/leafnode-nntp-os-x.org][Setting up on OS X]]
  - Licence
    - [[file:articles/2007/gpl-vs-bsd-license.org][BSD]]
    - [[file:articles/2007/gpl-vs-bsd-license.org][GPL]]
  - [[file:articles/2010/little-brother.org][Little Brother]]
  - Login
    - [[file:articles/2014/passwordless-registration-and-login.org][Passwordless registration and login]]
  - Losing weight
    - [[file:articles/2014/eating-right.org][By eating right]]
* M
  - ModSecurity
    - [[file:articles/2016/modsec-and-puppet.org][Configuring with Puppet]]
* N
  - [[file:articles/2006/playing-at-the-edge-of-ai.org][Neural Nets]]
* O
  - Objective-C
    - [[file:articles/2008/resizable-grid-of-calayers.org][CAConstraintLayoutManager]]
    - [[file:articles/2008/resizable-grid-of-calayers.org][CALayers]]
    - [[file:articles/2007/embedding-cocoa-frameworks.org][Embedding Frameworks]]
    - [[file:articles/2008/objective-c-feature-request.org][Feature Request]]
    - [[file:articles/2008/introducing-statistics-for-objective-c.org][Statistics]]
    - [[file:articles/2008/objective-c-syntax-sugar-wish-list.org][Syntax Sugar Wish List]]
  - Org mode
    - [[file:articles/2017/blogging-with-org-mode.org][For blogging]]
    - [[file:articles/2016/how-i-blog-this-week.org][Using with Jekyll]]
  - [[file:articles/2007/the-orient-express.org][Orient Express]]
* P
  - Parental Leave
    - [[file:articles/2014/good-ideas.org][Why it should be generous and ubiquitous]]
  - Photos
    - [[file:articles/2013/backing-up-photos-online.org][Backing up online]]
    - [[file:articles/2013/consolidating-iphoto-libraries.org][Consolidating and de-duplicating iPhoto libraries]]
  - Proportional Representation
    - [[file:articles/2017/electoral-reform-now.org][Voting system]]
  - Puppet
    - [[file:articles/2016/modsec-and-puppet.org][My change to the ModSecurity module]]
* R
  - Ranking
    - [[file:articles/2013/real-custom-rank-keys.org][Using real keys]]
  - Regular Expression
    - [[file:articles/2006/regular-expressions.org][Find words with three double letter groups]]
  - Resolutions
    - [[file:articles/2014/resolutions.org][2014]]
    - [[file:articles/2014/progress.org][2014 Progress]]
    - [[file:articles/2015/resolutions.org][2015 Resolutions]]
  - RSI
    - [[file:articles/2016/overcoming-rsi.org][Overcoming]]
* S
  - SBJson
    - [[file:articles/2014/delighting-users-with-sbjson-4.org][Streaming JSON]]
    - [[file:articles/2013/what-now-for-sbjson.org][What now?]]
  - Scala
    - [[file:articles/2013/scalatest-with-akka.org][Akka and ScalaTest]]
    - [[file:articles/2014/spray-example.org][Complete Spray DSL Example]]
    - [[file:articles/2013/injecting-akka-testprobe.org][Injecting Akka's TestProbe in place of children]]
    - [[file:articles/2013/scala-slick-postgresql-unit-tests.org][Slick and PostgreSQL Unit Tests]]
    - [[file:articles/2013/spray-routing-error-handling.org][Spray routing error handling]]
  - [[file:articles/2006/abandon-all-hope-the-terrorists-and-retailers-have-won.org][Security Theatre]]
  - [[file:articles/2014/good-ideas.org][Self-driving cars]]
  - Shell
    - [[file:articles/2007/piping-to-sh.org][Piping to -]]
    - [[file:articles/2007/renaming-lots-of-files.org][Renaming lot of files]]
  - [[file:articles/2005/new-headphones.org][Shure EC2]]
  - Slick
    - [[file:articles/2013/scala-slick-postgresql-unit-tests.org][Scala Unit Tests with PostgreSQL]]
  - [[file:articles/2014/smartphone-addiction.org][Smartphone Addition]]
  - Spray
    - [[file:articles/2014/spray-example.org][Complete Scala DSL Example]]
  - SQL
    - [[file:articles/2006/generating-bar-charts-with-sql.org][Generating Bar Charts]]
* T
  - Talk
    - [[file:articles/2016/berwick-academy-stem-talk.org][Berwick Academy STEM Talk]]
  - Tax Breaks
    - [[file:articles/2017/open-letter-to-anne-marie-mp.org][Tories' gift to those on high income]]
  - Terminal background colour
    - [[file:articles/2016/change-terminal-colour-ssh-os-x.org][Change on OS X from ssh]]
  - [[file:articles/2005/test-driven-development.org][Test Driven Development]]
  - Testing
    - [[file:articles/2006/a-lesson-in-testing.org][Its impact on interface design]]
  - [[file:articles/2015/tinkerbell.org][Tinker Bell (2008)]]
  - [[file:articles/2014/toddlercalm.org][ToddlerCalm 3-hour Workshop]]
* U
  - User Registration
    - [[file:articles/2014/passwordless-registration-and-login.org][Passwordless registration and login]]
* V
  - Virtual Machine
    - [[file:articles/2006/rise-of-the-machine.org][On writing one in C]]
* W
  - Working for Everyone
    - [[file:articles/2017/open-letter-to-anne-marie-mp.org][On the Tory pledge]]
