#+setupfile: ../../lvl-2.org
#+title: Nuisance Calls
#+date: <2015-02-04>

I'm interrupted far too often by cold-callers, PPI spammers, or even
just from people calling the wrong number. Last week my Out Of Hours
support phone got an SMS from a hospital laboratory saying “your test
result is normal”. I've been thinking about ways to reduce the number of
nuisance calls without hampering the usability of phones too much.

I think part of the problem is that phone numbers are too short: we've
run out of numbers. (When you get a new number, someone has likely had
that number before you. Who knows what they were up to?) A more serious
problem is that the numbers have no check sums. Mistype just one digit
and you end up calling the wrong number. With a good check sum you could
instead receive a helpful message saying that the number you typed
contained an error, and in some cases could even tell you which digit
was incorrect!

A more serious pest is the PPI spammers and many cold-callers that use
an [[http://en.wikipedia.org/wiki/Auto_dialer][auto-dialler]]. They work by calling many people at a time and either
play a recorded message or connect punters to an operator. I receive
PPI spam several times a week now from multiple different numbers.
Some even call from overseas!

Dealing with short numbers should be simple. Their length has been
extended many times before. (Many years ago, the local shop where I grew
up had phone number 11.) The problem is they don't go far enough: I
don't see why we can't just double the length of phone numbers. (Nobody
actually /memorise/ phone numbers these days, do they? If so, this could
be an incentive you to kick that habit. Or, make it actually impressive.
Either way, it's a win.) Obviously we could retain the current numbers
for anyone that would like to put their number in adverts, leaflets,
etc. Doubling the length of phone numbers could help combat
auto-diallers, in that it would become much, /much/ more resource
intensive to simply try guessing numbers. Phone companies could also
charge a small fee for connecting you to a number that doesn't exist, to
further deter auto-dialling.

While longer numbers would mean not having to use a recycled number, and
making auto-dialling impractical, it is not enough. It offers no
protection from people giving or selling your number to people you don't
want to talk to. We know that blacklisting doesn't work: like me I'm
sure you block every cold-caller you encounter, but every week they're
using new numbers. We cannot block them in advance. Or can we?

This is where white-listing comes in. Apple's iPhones have a feature
called DND (Do Not Disturb), which allows you to specify a time range
when your phone should not make a noise when receiving calls or
messages, so you can avoid being woken up in the middle of the night for
example. More interestingly, they allow you to specify that /some/
people in your contacts can get through to you, /even if DND is on/. I'm
close to turning my phone on DND permanently, but allowing access from
family and friends in my contacts. Although, you would then still see
missed calls, so if that annoys you (it does me) it's not a complete
solution either.

PS: I've found out that Windows phones allow you to block callers with
no caller id. This is something that I've wanted for a long time.
Hopefully Apple will implement this as well. Or maybe I'll be buying a
Windows phone next...?
