#+title: 2015 Resolutions
#+date: <2015-01-01>
#+index: Resolutions!2015 Resolutions

Happy New Year! The title of this post makes it look like I have a
silly number of resolutions this year, but fear not: I've managed to
limit myself to five. Before getting to them, however, let's first
review how I did on my [[file:~/blog/articles/2014/resolutions.org][2014 resolutions]]:

- CodeClub: failed! I did however sign up as a STEM Ambassador, and
  were in talks with a school to start a club---but didn't find a way
  to commit the required time.
- Lose weight: success! Although I didn't get to 75kg by April, I did
  by August---and my weight continues to drop. It seems I am able to
  [[file:~/blog/articles/2014/eating-right.org][lose weight by eating right]].
- Blogging: success! I managed fourteen blog posts last year
  (including three on the [[http://techblog.net-a-porter.com/author/stig/][company blog]]) which is one shy of my goal,
  but I'm claiming this year's record-length /Yuletide/ letter to family
  as my fifteenth.
- Socialising: success! Though I didn't manage to arrange a meet with
  old friends 12 times last year, as I intended, I'll count this as a
  success as I've met up with /new/ friends my son and I have made at
  the playpark.

Overall I'm quite pleased. It was a busy year, but one where my health
and wellbeing took a massive turn for the better. I weigh less now than
I've done since I did competetive Judo in my teens.

My resolutions for 2015 are to:

1. Continue writing, but I'll set the bar a little lower this year:
   twelve posts on this blog.
2. Improve my [[http://stackoverflow.com/users/5950/stig-brautaset][StackOverflow reputation]] from current 1808 to at
   least 2500.
3. Continue learning Clojure (a Lisp targetting the JVM) by writing a
   web application and getting at least ten users.
4. Make an attempt at improving my guitar playing by going through the
   first ten chapters of [[http://www.noad.com/SGP1ndx.html][Solo Guitar Playing]] by Frederick Noad.
5. Go hiking in Northumberland and camp out at least once.

All realistic & achievable goals, I think, but not without putting in a
little effort. I am looking forward to the challenge! Please do feel
free to prod me about progress on any of these!
