#+title: Tinker Bell (2008)
#+date: <2015-02-03>
#+index: Tinker Bell (2008)

A talented young engineer struggles to overcome social norms and to be
allowed to join her friends on their annual field trip.

Here's a summary (beware spoilers):

The film starts with Tinker Bell appearing in Pixie Hollow: a magical
island in Neverland where seasons never change. Ruled by the benevolent
Monarch /Queen Clarion/, the fairies make much hoo-ha about---and
organise themselves into groups based on---their /Talent/. They don't
have to suffer the trials and tribulations of childhood and education
though: Tink springs to life fully formed both physically and mentally,
born from a child's first laugh.

Tinker Bell's talent for engineering (or "tinkering" as it's referred
to) is unusually strong, earning her the chagrin of Vidia---a
fast-flying fairy. Fellow engineers Clank and Bobble do their best to
welcome Tink into their fold, where she is expected to make and repair
tools for the rest of the fairies.

Tinker Bell soon meets and befriends Silvermist, Rosetta, Iridessa &
Fawn---a water, garden, light, & animal fairy respectively---and learns
that they will be going on a field trip to prepare the /Mainland/ for
Spring. When Tink learns that the engineers /don't/ go on field trips,
our hot-headed Heroine decides to abandon her promising career in
engineering and train for a vocation with more prospects of travel.

Her friends are initially supportive but when they see how hapless Tink
is with water, light, and animals, they start to think it's a bad idea.
Depressed at her failure to adopt a nature-fairy talent Tinker Bell
finds a broken music box and proceed to fix it. Her friends secretly spy
on her and note how skilfully and naturally she puts the box together,
and how it cheers her up. Because of this Rosetta refuses to help Tink
become a garden fairy, telling her not to throw away her talent.

Getting increasingly desperate Tinker Bell asks Vidia for advice. Vidia,
still holding a grudge from Tink (accidentally) causing her to be pelted
with berries, decides to play a trick on her. The outcome is that Tink
accidentally destroys all the fairies' preparations for Spring, and
distress grips Pixie Hollow. It will take months to redo the work, and
Spring is in danger: if it doesn't come on time the world risks entering
into an ice age.

/Can Tinker Bell draw on her unusually strong talent to save the day?/
You can probably guess the answer to that, but there's no shame in just
watching the film to find out. I've watched it /many/ times with my
3-year old son and I still enjoy it. It is refreshing to see a film
where the heroine's chief worry isn't who she is going to be married off
to.

Although I'm not entirely sure it applies as the fairies rely on asexual
reproduction, I'll rule that it passes the
[[http://en.wikipedia.org/wiki/Bechdel_test][Bechdel test]]. The fairies
certainly /look/ male and female, and there's hints at attraction
between them. (But nothing unsuitable for children.)
