#+title: Bad Typesetting
#+date: <2006-11-28>

While I'm on the subject of writing, I thought I'd sneak in a note about
typesetting. I'm a closet typesetting geek; you probably /have/ to be to
care about whether to use an en-dash or a plain dash to separate ranges
of numbers, for example. In case you're wondering: use an en-dash---the
difference is appreciable.

There are some beautifully typeset books (TAOCP, for instance) and some
really atrocious ones. One of the worst offenders is /Just For Fun/;
Linus Torvalds' autobiography. Its constant changing of fonts, font
weights and styles appears to be the work of a rabid monkey on acid
rather than an actual human typesetter. It's headache-inducing at best,
and very nearly made me put the book down and not finishing it.

Now, what this typesetting /did/ manage was to make me remember the
book. Unfortunately the only thing I can remember is that the
typesetting was excruciatingly bad. From this I infer that the content
wasn't all that great, but that's a blog post for another time.

I don't quite know what came over me, I just needed to get this rant off
my chest. My usual happy & chirpy tone will resume shortly.
