#+title: Hippies
#+date: 2006-08-13

Nadia and I are turning into hippies. I bake bread for our breakfast and
Nadia cook most other meals from first principles. We save plastic by
reusing bags when we go to the shop, and generally refuse a bag when we
only buy one or two items. We don't have a TV.

It started getting out of hand, however, when we moved to Islington a
couple of months ago. I now walk to work, we got rid of the car and
hung Nadia's bike in the communal bikeshed. There's the wonderful
[[http://www.lfm.org.uk/isling.asp][Islington Farmer's market]] every Sunday where we can pick up seasonal
fish, meat and veg; and we can get organic meat and veg delivered
straight to the door (somewhat ironically, we lived too far away from
the city centre earlier).

Before we knew it the detergents became eco friendly, the soap turned
organic (it has /oats/ in it, fer/crying/outloud) and we're eating new
grains like guinoa and millet. The fruit and veg we eat varies with
the season; Nadia wants a small herd of goats; and flocks of ducks,
chickens, pigeons & quails; not to mention a [[http://www.google.co.uk/images?q=fjord+horse][fjord horse]] or two.
