#+setupfile: ../../lvl-2.org
#+title: Target Reached!
#+date: <2006-03-15>

At the gym today I finally managed to meet the target set for me back in
November last year: use a X-trainer and cover two arbitrary (as far as
I'm concerned) units of distance at level 13 in less than 10 minutes. I
clocked in at 9 minutes 58 seconds today, an improvement of 5 seconds on
my previous best two days earlier.

I had a steady pulse of around 176 for the first eight minutes or so,
then a little over 180 for the sprint. Six months ago this would
probably have put me in a coma. Now, however, I was able to continue my
program after having spent a minute sprawled over the machine gasping
for air.

I've had fairly slow progress since the middle of January; I had a
3-week lapse over Christmas that made me unable to do more than about
five minutes, so I pretty much had to start from scratch. Much to my
surprise, however, the last week and a half things have suddenly started
to fall into place and I've improved by over 30 seconds.
