version: 2.1

executors:
  nixos:
    working_directory: ~/blog
    docker:
      - image: nixos/nix
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

commands:
  enable-flakes:
    steps:
      - run: mkdir -p ~/.config/nix
      - run: echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf

jobs:
  build:
    executor: nixos
    steps:
      - checkout
      - enable-flakes
      - run:
          name: Tangle CSS
          command: nix run .#tangle-css
      - run:
          name: Publish Blog
          command: nix run .#publish-blog
      - store_artifacts:
          path: ~/blog/_site
          destination: html
      - persist_to_workspace:
          root: ~/blog
          paths:
            - '_site'

  upload:
    executor: nixos
    steps:
      - checkout
      - enable-flakes
      - attach_workspace:
          at: ~/blog
      - run: nix run .#sync-to-s3
      - run: nix run .#cf-invalidation

workflows:
  pr:
    jobs:
      - build:
          filters:
            branches:
              ignore: trunk

  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: trunk
      - upload:
          requires:
            - build
