#+setupfile: ~/blog/lvl-2.org
#+title: Open Letter to Anne-Marie Trevelyan MP
#+subtitle: How are the Conservatives "working for everyone"?
#+date: <2017-05-20>
#+category: Soapbox
Dear [[https://www.teamtrevelyan.co.uk/][Anne-Marie]],

I live in your constituency and I have a question.

I am wondering how the Conservatives can say you are "working for
everyone" whilst giving the 15% of top earners[fn:1] a tax break /5
times/ the size of low earners[fn:2]? How is it fair that people on
minimum wage should only get a £100 tax break but those who earn more
than £45,000 gets a £500 tax break?

Now consider the ISA offerings you bumped the limits of to £20,000 per
year. It would /technically/ be possible to get this benefit if you earn
£25,000 per year---assuming you live for free, eat for free, and spend
no more than 75 pence per day[fn:3]. Yet, the median salary in this
country is roughly £21,000 before tax[fn:4], which means half the
population cannot possibly get this full benefit even if they save /all/
their earnings. You need to be among the top 10% of higher
earners---which means you have a salary of more than
£35,345[fn:7]---to have a fighting chance of making the full use of
this benefit. It is clear that this is not a benefit for everyone, but
for the few: the elite.

To finance these tax cuts and benefits for high earners you cut
benefits to the poorest and most vulnerable in this country. You're
cutting the Employment Support Allowance (ESA) by £29/week. You're
cutting child tax credits, worth £545 per year. Further you are
freezing benefits, including JSA, ESA, child benefits and some housing
benefit payments[fn:2]. All the while a rising number of people are
reaching out to food banks to make ends meet[fn:5].

The Conservatives say you are "working for everyone". It's time you
start acting like it.

Stig

* Footnotes

[fn:1] Estimate for the percentage of people on higher tax band,
myself included. Source:
https://www.theguardian.com/news/datablog/2014/jan/27/how-many-pay-top-rate-of-income-tax-uk

[fn:2] Personal allowance increased from £11,000 to £11,500, which
equals a £100 tax break. But the 40% rate of tax will move from
£43,000 to £45,000. This will save higher rate taxpayers an /additional/
£400. Source: http://www.bbc.co.uk/news/business-39441970

[fn:3] At £25,000 per year https://www.uktaxcalculators.co.uk/ says
you should have about £20,279.68 left after tax.

[fn:4] Source: https://en.wikipedia.org/wiki/Income_in_the_United_Kingdom#Taxable_income

[fn:5] Source:
http://www.independent.co.uk/news/uk/home-news/food-bank-usage-at-record-high-reveals-trussell-trust-a6984921.html

[fn:7] Source: https://en.wikipedia.org/wiki/Income_in_the_United_Kingdom#High_income
* Abstract                                                         :noexport:

I ask how the Conservatives can say they are "working for everyone"
whilst giving extra tax breaks and benefits to the 15% of top earners,
and at the same time cutting benefits for the poor.

