#+title: Moving in
#+date: <2006-04-26>

Thursday (20th) at lunchtime I got a phonecall from Nadia. I had
received a letter from my solicitor saying he needed about three
thousand pounds (for stamp duty, 1 month's advance rent & service
charge, his and the seller's solicitor fees) to complete the sale. Since
we had arranged to have removers come and pick up our stuff the next
morning things were looking bad. After a bit of fretting and calling my
solicitor to confirm the requirement, and the bank to transfer money, it
was all sorted however. Co-workers were impressed with me coughing up
that kind of money in such short notice, but I assured them that
(unfortunately) it is not a party trick I can pull very often. It will
be a very long time till I can do it again.

After packing boxbes till late at night Thursday evening we had a good
night's sleep before getting up early for more frentic packing before
the removal men arrived. They managed to get everything into the truck
this time (when we moved into the flat in Stanmore they I believe they
had to round up a second truck). Quite frankly with all the things we've
thrown away and given to charity lately I'm surprised we had anything to
move /at all/.

After picking up a surprising number of keys in Clerkenwell we met the
removal men at my new flat at 1:30pm. Nadia went off to Islington
council to get a parking permission while I guarded the lorry with all
our stuff so nobody would run off with it. I helped out a bit by moving
stuff from the inside of the truck to the back for easy picking up. The
removal men exploited this fact and ran up and down the stairs /like
demons/, giving me no chance to sit down and take a rest.

The removal men left at 4pm, about the same time Nadia came back from
the Counsil, parking permit in hand. She told me that before she left
for the counsil she had emptied a year's worth of "welcome new
customer!", "you owe us money" and "we're coming to get you now!"
letters from gas, electricity and tv licensing people.

The rest of the afternoon and evening was spent setting up our one piece
of furniture, an oak dining table; unpacking boxes; trying to figure out
how the hot water and heating worked; and clear enough floorspace to fit
our mattresses. Unfortunately our neighbours were awfully inconsiderate
and didn't have an open wireless access point as I would have liked to
check my mail...
