#+setupfile: ~/blog/lvl-2.org
#+title: Moving-in Party
#+date: <2006-04-26>

[[http://www.sem-jacobsen.no/][Stein]] came over from Norway Sunday morning. We spent a few hours
catching up and reminiscing about the past before going to [[http://www.yosushi.com/][Yo! Sushi]]
at the [[http://www.n1islington.co.uk/][N1 centre]] (beware, eeevil site with music) for dinner with
Nadia. Nadia went home afterwards while we went to the pub. The rest
of the evening is a bit blurry, but I woke up the next day partly
dressed and with a severe hangover. A plastic fork in my pocket
revealed that I'd had kebab the previous night.

After drinking lots of water and eating dry bread we decided that we
needed some fresh air, so Stein and I walked to the office and picked up
Nadia's iBook (she had it delivered there since we were in the middle of
a move). Nadia stayed home looking after the washing machine; I had put
new washers in and we were running it for the first time in almost three
years.

On the way back we got a bit lost trying to take the bus and save
ourselves some walking. Not knowing quite where we were we had English
breakfast for lunch, served by a very /enthusiastic/ young man. We were
then pointed in the direction of Essex Road and started making our way
back home. On the way there we accidentally found the pub I'd invited
people to that evening. This was rather lucky, since I still have no
internet connection at home and I'd forgotten to print out directions
there from my flat.

Monday evening Stein, Nadia and I went to the [[http://www.beerintheevening.com/pubs/s/31/3133/Canonbury/Canonbury_Place][Canonbury Tavern]]. Not
long after more friends than I thought I had started turning up--more
than 20 people in the end. Dean said I owed him a alot of money as he
had paid many of them to turn up (at least I /hope/ he was joking).
Thanks to all who came; you made it as soon to "my perfect night out"
as you can reasonably assume ever experiencing.
