#+title: ToddlerCalm
#+date: <2014-06-26>
#+category: Reviews

"ToddlerCalm" is the founding principles we use to raise our son. They
are from a book called "ToddlerCalm: A guide for calmer toddlers and
happier parents" by Sarah Ockwell-Smith. It is available for [[http://www.amazon.co.uk/ToddlerCalm-calmer-toddlers-happier-parents-ebook/dp/B00CQ5R186/ref=sr_1_1?s=books&ie=UTF8&qid=1394282509&sr=1-1&keywords=toddlercalm][Kindle]]
and [[http://www.amazon.co.uk/ToddlerCalm-calmer-toddlers-happier-parents/dp/0349401055/ref=tmm_pap_title_0?ie=UTF8&qid=1394282509&sr=1-1][paperback]]. In the UK there's also a [[http://toddlercalm.co.uk/pages/parent_classes.html][ToddlerCalm 3-hour workshop]].
We have found what we learned invaluable in helping us understand what
our son is going through growing up. (And thus how to deal with him.)
This post is about what we learned from reading the book and attending
the workshop.

My wife and I both read the book before we attended the workshop, which
was led by clinical child psychologist Victoria Montgomery. For me the
workshop was the more powerful of the two; however, I think it was
useful to have read the book as it meant I had some questions prepared.
The book (& course) does teach some tricks for "how to deal with
tantrums" but more than anything it helped us understand what we can
expect from him at his age, and thus we know not to expect too much.
You'd be surprised how much more you can handle of particular behaviours
if you know that it is perfectly normal (despite what others say!) :-)

My biggest issue was his night-time sleep---or rather lack of it. I had
this expectation that our son should fall asleep at about 8pm, and I was
getting stressed out by him failing to do so. We tried everything:
carrying him around for hours in a dark room, singing to him or playing
calming music. It didn't help much, and we were getting exhausted. The
course taught us that it is entirely normal for toddlers to sleep
irregularly until about 4, and as soon as we learned that this was
normal it became a lot easier to cope with. He's not abnormal: he just
doesn't sleep as much /as we would like/. He doesn't go to sleep much
earlier now, but it doesn't bother us much. Bedtimes are much less
stressful.

One of the most important things I learned about was the [[http://en.wikipedia.org/wiki/Theory_of_mind][Theory of
Mind]] and its importance on social interaction. This is what allows us
to see things from another person's perspective. Until toddlers
develop this they simply won't understand the importance of sharing,
for example, or why it's bad to hit other kids. They don't have the
mental development for it. And the real clincher is how late Theory of
Mind develops---much later than I would have thought. According to
Victoria only 10% of kids develop it as early as 4 years, and /10%
still haven't developed it at age 6/.

Another point Victoria was keen to stress was how kids' limited brain
development makes them prone to be overcome by emotion. Their animal
brains take over and they are no longer able to think rationally, or
producing or understanding speech. This is when they need your
compassion and understanding the most. Just about the /worst/ you can do
in this situation is punishing your child, for example by calling a
time-out and sending the kid to the naughty step. They simply won't
understand why you're being so mean to them. Victoria underlined this
with a thought experiment: try to imagine you've had a bad day and
you're crying & hugging your partner when she or he comes home. But
instead of asking you what's up and giving you their full attention,
your partner drag you off to a corner and insists you sit there until
you "have calmed down and stopped crying". /How would it make you feel?
What do you think you would learn from the experience?/ If you don't
think you would learn anything positive from it, do you think a child,
with their much more immature brain development, would?

Meal times also used to be stressful for us. Again, a lot of that stress
came from wrong expectations: that he would eat a balanced meal every
mealtime, and that he would eat at a time of our choosing. We knew that
we didn't want to force him to eat, so we had to learn to let him eat
what he wants at meal times. Within limits, of course, as he chooses his
food from a selection of foods we provide. One interesting thing we've
found is that our son goes through phases exploring certain types of
food. For example he refused anything green for a while, but at the
moment broccoli is one of his favourites. He also will sometimes not eat
things if they are mixed together, but will wolf them down separately.
We also reasoned that we have evolved to graze---we doubt stone-age man
had three square meals a day, with no snack in between---so we offer
fruits and berries liberally. As long as he's healthy & developing well
we're happy to let him have a bit of control over his food. In hindsight
his diet is actually fairly varied; even if every /meal/ is not.

As an aside, it could be that the whole concept of a "balanced diet"
is flawed. If you look around a bit it turns out lots of tribal
societies eat incredibly unvaried diets. Eskimos, for example, eat
fish and seal fat almost exclusively: no vegetables at all. (Iceberg
lettuce is not named after its growing conditions, after all.) The
[[http://en.wikipedia.org/wiki/Maasai_people#Diet][Maasai diet]] is also predominantly meat.

Note: There is also a book [[http://www.amazon.co.uk/BabyCalm-Calmer-Babies-Happier-Parents-ebook/dp/B008IQY7PW/ref=sr_1_1?ie=UTF8&qid=1403733078&sr=8-1&keywords=babycalm][BabyCalm: A Guide for Calmer Babies and
Happier Parents]] and accompanying [[http://babycalm.co.uk][BabyCalm website]] for parents of
children that haven't reached toddler-hood yet. I haven't read that,
but based on my experience with ToddlerCalm I will definitively snap
it up once we have a baby in the house again.
