#+title: My hiring experience as a submarine sonar operator in the Norwegian Navy
#+begin_abstract
This is a transcript of a lightning talk I gave at a company "all
hands" get-together. I tell the story of my "hiring experience" as a
sonar operator on a submarine in the Norwegian Navy. To tie it into
work, I included a little hiring-related lesson at the end.
#+end_abstract
#+category: Talks
#+category: Hiring

As some of you know I spent a year on a submarine. This is the story
about how that came about.

Norway has compulsory military service, and I wanted to make the best
of it. At my assessment & induction meeting I picked the Navy for
three main reasons:

- I thought I'd be able to sleep in a dry bed every night, instead of
  a wet sleeping bag. (This assumption was /almost/ correct.)
- I had heard submariners had the longest expected lifespan if
  deployed in a hostile situation.
- Thirdly I had seen the film [[https://itunes.apple.com/GB/movie/id211292501][The Hunt for Red October]] and for some
  reason the role of sonar operator on a submarine seemed really
  glamourous to me.

Everyone that enters the Norwegian Navy starts with six weeks basic
training on the same base. We received training, a fitness regime, and
lots of tests. I remember scoring 2/7 on my hearing test, and thought
my chance of becoming a sonar operator was now over.

At the end of my basic training I could finally apply to a specific
branch of the Navy. As I had expected, sonar operators on submarines
required hearing score of 7/7. But, what I hadn't expected was that
/every/ branch of the Navy required at least 3/7. I didn't qualify for
/anything/! Yet, I was told I had to pick _something_, and I thought I
might as well shoot for the stars. I applied to become a sonar
operator, and was accepted. I spent the next six weeks on a more
specific submarine training course.

- All submariners had to learn to escape from a submerged submarine
  through an airlock. We practiced this in a 20-metre deep swimming
  pool at the base.
- We also had to memorise the location of all the valves on pipes
  penetrating the hull, so we could close these in an emergency.
- Sonar operators additionally have to learn to classify ships by the
  sound their propellers make. Is it a fishing boat, merchant-, or
  warship? And are they likely to be friend or foe?
- We also did more physical tests, including another hearing test
  which confirmed the result of the previous: my hearing was pretty
  bad. However, it was a bit more specific in /how/ it was bad[fn:1].

At the end of the six weeks we got to choose which submarine we wanted
to serve with. I had the highest score in the sonar operator test and
normally this meant I would get first pick. But, the officer in charge
seemed a bit hesitant and asked me: "wasn't there something wrong with
your hearing?" I didn't want to lie. But I also didn't want to
disqualify myself. I took a slight gamble and answered him with a
question: would I have managed to get the best score on your test if
there was? I guess that satisfied him, because instead of freezing my
bottom off in Norway the following winter I was on the first Norwegian
submarine to ever attend a NATO exercise in the Mediterranean.

When I wrote up this story I realised it contains a lesson relevant to
hiring: people who don't satisfy all the proxy requirements in your
job ad may still be a good fit for your role. Please make sure the
requirements you put in job ads are actual /requirements/, and not "nice
to have"s.


* Footnotes

[fn:1] They split my hearing range in low and high register for each
ear, so four in total. I had poor response to one frequency in each of
these "quadrants", but otherwise normal hearing.
