#+setupfile: ../../lvl-2.org
#+title: How to Support My FOSS Work!
#+date: <2018-01-01 Mon>
#+begin_abstract
I present four ways you can support me if you have (or continue to)
benefit from my work on Free and Open Source Software (FOSS).
#+end_abstract

I've been contributing to Free and Open Source Software (FOSS) for
over 15 years now. I've never charged for this work, though lots of
people have benefited from it.  You could argue I'm /absurdly/ late to
the table, +but I've now set up profiles on Patreon and Liberapay to
allow people to pay me a (small) monthly amount for this work.+
Alternatively, you may prefer a one-off donation via [[https://paypal.me/stigbra][PayPal]], or buying
me something from my [[http://amzn.eu/bRH7hfI][Amazon Wish List]] instead.

:NOTE:
As of June 2018 I decided to end the Patreon and Liberapay
experiments. You can still use the Amazon Wishlist and PayPal options.
:END:

I only expect to recover a /small fraction/ of the time, effort and
money I've spent developing and supporting FOSS software.  If you have
benefitted from my work, please consider a small regular contribution.

What kind of work do you do, I'll pretend to hear you ask?

Well, I started my best-known project [[https://github.com/stig/json-framework][SBJson]] (aka JSON-framework) in
September 2007.  It is a JSON parser and generator written in
Objective-C, for iOS and macOS applications.  Back when I started this
project Apple didn't provide JSON parsing, so a lot of early iOS
applications used it. Even Apple has been using it to enhance iOS
since iOS 3.  SBJson is now very mature, so doesn't require a lot of
work.  But it received several important bugfix releases and a major
version release as recently as 2016, and I still try to answer
SBJson-related questions on StackOverflow.  This takes time and
energy, and incurs sundry costs related to hosting, which is getting
increasingly difficult to justify.

Recently I write mostly in Emacs Lisp, of which my most popular
project is [[https://github.com/stig/ox-jira.el][ox-jira.el]]. This is an Emacs Org mode export backend, so
you can write in a [[http://karl-voit.at/2017/09/23/orgmode-as-markup-only/][remarkably sane markup language]] and export to the,
ahem, /esoteric/ JIRA (and Confluence) markup language.

Find more projects at https://github.com/stig
