#+title: My Musical Goals for 2019
#+begin_abstract
I list my musical goals for 2019, and touch briefly on achievements in 2018.
#+end_abstract
#+category: Music

2019 is going to be my "year of the guitar". I worked through most of
[[https://www.justinguitar.com][Justin Sandercoe's]] beginner lessons in 2018, and I look forward to
starting his intermediate lessons.

I got my first electric guitar 25 years ago, but until mid 2017 I was
only able to play some riffs and butcher one or two solos.  There had
been periods of years where I barely touched my guitar at all. Then,
about mid 2017 I decided I wanted to really learn to play and
contacted a local guitar teacher.  When he moved countries a few
months later I switched to use [[https://JustinGuitar.com][JustinGuitar.com]], near the beginning
of 2018.

One of the best things I got from Justin was to learn not only what to
practice, but /how/ to practice. Having completed most of his beginner
course I'm now able to play along to the original recording for 10+
songs well enough to have a lot of fun.

For my birthday in April 2018 I upgraded my guitar amp to a [[https://usa.yamaha.com/products/musical_instruments/guitars_basses/amps_accessories/thr/index.html][Yamaha THR
10]], to make it easier to practice. Part of this was because my old amp
(a Fender Frontman 25 DSP) was impossible to set to a useable volume
settings. The only ones I could find was /not audible/ and /WAY too
loud/. It was also too big and ugly for the living room. On the other
hand, the THR works even on batteries, and fits on a shelf when not in
use. It even has USB connection so I can record straight to
GarageBand.

As a reward for my progress in 2018, I traded in four low to medium
end guitars[fn::All the three I owned already + my wife's
guitar. (She's focusing her energies elsewhere, and we got a better
trade-in value than we've been failing to sell it for on
Gumtree/Facebook.)] and my old amp for a really good guitar in the
final days of 2018, hoping it would help me keep momentum going
in 2019. The main drawback of the new guitar is that it weighs as much
as the other four put together, and is too precious to me to take
travelling. So, I'm now also in the market for a cheap & light travel
guitar, and have my eyes on a [[https://www.hofner.com/hofner-shorty-blau.html][Hofner Shorty]].

Getting back to my musical goals for 2019, [[https://www.youtube.com/watch?v=rCUicrtYabU][Justin recommends]] sharing
your goals so your friends can keep you honest, and this is my attempt
at that. He recommends one-year long-term goals, 6 months medium term
goals--to make sure you're on track for the long-term ones--and
monthly short-term goals. I actually set some up three months ago, but
they were too long-term[fn::10+ years for long term, 5 years for
medium term, and 1 year for short term. That might work for
professional musicians working toward their life ambitions.] to work
for me, and I am confident this will work better.

Without further ado, here are my goals for 2019:

1. Jam with other people at least six times
2. Start and complete Justin's "Green" grade
3. Record myself playing once a month to track progress
4. Learn 10 new songs
5. Stretch goal: complete Justin's "Blue" grade
6. Stretch goal/treat: start building a pedal board

To make sure I'm on track to complete those by the end of 2019, I aim
to complete the following by the start of July:

1. Save up for and buy a travel guitar for taking on work trips,
   holidays, and potentially to local Jam sessions if it's good enough
2. Jam with other people (maybe at work trips?) at least twice
3. Finish Justin's beginner/consolidation modules
4. Complete two modules of Justin's "Green" grade
5. Learn 5 new songs
6. Become more procifient using my looper pedal
7. Research how to record myself on video

Finally, here are my goals for January:

1. Practice for and complete [[https://www.justinguitar.com/guitar-lessons/grade-3-quickfire-test-et-306][Justin's Ear Training Grade 3 Quickfire
   Test]] and improve on my 75% score from last time
2. Enquire at the local music shop about local people amenable to
   jamming / playing together
3. Finish Justin's beginner consolidation modules that I'm currently
   working on
4. Retire my current set list [fn::Most of them still needs work, but
   I am thoroughly tired of most of them now and want a break and a
   "change of scenery" for a bit. I'll get back to them, probably.]
   and pick some new songs to practice
5. Record myself playing AC/DC's "You Shook Me All Night Long"

So, that's a bit about my progress and my musical goals for 2019. I'm
hoping to come back to this again this year to provide updates, but my
blogging frequency record isn't exactly stellar, so whether I manage
remains to be read!

