#+setupfile: ../../lvl-2.org
#+title: Blade Trinity
#+date: <2005-10-08>
#+category: Reviews

Though Snipe's character was one-dimensional and dull as ever, [[http://uk.imdb.com/title/tt0359013/][Blade
Trinity]] on a whole is actually quite enjoyable. This was pulled off by
giving the great support cast more screen time. The story was thin as
usual, but I don't let that get in the way of good entertainment.

Blade's two sidekicks, motormouth wise guy Hannibal King (Ryan Reynolds)
and eye candy Abigail Whistler (Jessica Biel), were both good.
Unbeknownst to Blade their team were doing their homework killing
vampires and figuring out what the vampires were up to, before coming to
Blade's help busting him out of prison. The fool had managed to get his
friend killed and himself arrested. Blade, ever thankful, didn't want
their help at first but knew he could not carry the film alone so gave
in in the end.

Of the vampires I particularly liked Parker Posey's character Danica
Talos. She had a wonderful world-weary rock-star feel about her, as if
she found everything dreary and almost terminally boring. Her
interactions with King got her juices flowing though; you could /feel/
him winding her up.
