#+title: New Headphones
#+date: <2005-12-02>
#+index: Shure EC2

Earlier when I've griped about the iPod Shuffle, saying it needed a
dynamic compressor, [[http://twoshortplanks.com/][Mark Fowler]] told me I just needed better
headphones. I didn't really take him too seriously as I didn't think
there could be that much difference between in-ear headphones.

Nevertheless, when my headphones failed recently, I decided to try the
[[http://shop.ipodworld.co.uk/iPodWorldSite/product/all_iPods_Favourites/SH01.htm][Shure EC2]] he were recommending. I found them a bit weird and painful
to wear to start with (they don't just go in the ear, they go inside
the ear canal) but that was just a matter of finding which of the 9
different sizes and types of sleeves fit my ears best. Because they
fit so snugly into the ear canal, they significantly reduce the amount
of surrounding noise that you hear. This means I don't have to jog the
volume on my iPod up and down all the time if a song has quiet and
loud parts; the effective dynamic range is much greater. They also
manage much lower frequencies than I've heard in any other headphones.

In short they have made it enjoyable to listen to music on my iPod
again. That makes them worth the (rather stiff) price, in my opinion.
