#+setupfile: ~/blog/lvl-2.org
#+title: Little Brother
#+date: <2010-01-09>
#+category: Reviews

[[http://craphound.com/littlebrother][Little Brother]] by Cory Doctorow is a whirlwind of a novel,
downloadable in various electronic formats from the author's website.
This book should be compulsory reading in schools. Actually---scratch
that. It should be compulsory reading for /everyone/.

Here's the lowdown:

#+BEGIN_QUOTE
  Marcus, a.k.a “w1n5t0n,” is only seventeen years old, but he figures
  he already knows how the system works--and how to work the system.
  Smart, fast, and wise to the ways of the networked world, he has no
  trouble outwitting his high school's intrusive but clumsy surveillance
  systems.

  But his whole world changes when he and his friends find themselves
  caught in the aftermath of a major terrorist attack on San Francisco.
  In the wrong place at the wrong time, Marcus and his crew are
  apprehended by the Department of Homeland Security and whisked away to
  a secret prison where they're mercilessly interrogated for days.

  When the DHS finally releases them, Marcus discovers that his city has
  become a police state where every citizen is treated like a potential
  terrorist. He knows that no one will believe his story, which leaves
  him only one option: to take down the DHS himself.
#+END_QUOTE
