#+setupfile: ../../lvl-2.org
#+title: First Dim Sum
#+date: <2001-10-28>

Wow. Time flies when you have fun, they say. I think "they" may be
right. I barely get time to wonder what to do with one week before I
have to wish it farewell.

The running is starting to pay off. I notice less stress in the running
itself, it's also easier to stay awake at other times. I even can fit
into my old clothes better than before, but that might be a illusion, or
due to other reasons.

Went to a Chinese restaurant and had Dim Sum. The food was ordered for
me in Cantonese, so I didn't have a clue what it was until I dived in. I
tried what looked like "something from the sea" before I was told it was
cow's stomach. Ouch :) It didn't taste very much, but it had a
consistence I am not at all used too. It was fun trying tho :-)

I also had chicken feet (yes, feet, not legs), some kind of sweet dough
balls with meat inside (quite nice); a mix of prawns and pork; some
bright white steam-cooked buns with pork inside (those were really nice)
and special fried rice. We were going to have Tofu for dessert, but they
didn't have any left.
