#+setupfile: ~/blog/lvl-2.org
#+title: Avenue Que?
#+date: <2008-06-05>
#+category: Reviews

[[http://blog.unixdaemon.net/][Dean]] and I went to see Avenue Q last night, having heard rave reviews
about it. Plus, he found some cheap tickets, which turned out to be
really good. There was only one problem: we both hated the show. So
much, in fact, that we left at the intermission and didn't bother
going back for the second part. It was just too dull to waste another
hour of our lives on.

It wasn't the fault of the actors. (Not all of them, at least.) In
particular, [[http://www.avenueqthemusical.co.uk/the-show/cast/mark-goldthorp.php][Mark Goldthorp]] animated his characters with great skill.
And [[http://www.avenueqthemusical.co.uk/the-show/cast/rebecca-lock.php][Rebecca Lock]], the leading monster, did a hell of a job on the
singing front. But skilful actors is not enough; it has to be
entertaining too, and this one was not. It was just full of
platitudes.

This came as a bit of a surprise. We seemed to be the only ones in the
audience not enjoying the show. And it came with recommendations from
people that we thought of as friends that have (allegedly) been to see
it several times. Now we need to re-assess these friendships: /real/
friends wouldn't trick friends into viewing Avenue Q.

The pulled-pork sandwich I had afterwards lifted the evening somewhat.
