#+title: Abandon all hope
#+subtitle: The Terrorists And Retailers Have Won
#+date: <2006-12-19>
#+category: Soapbox

Leaving London Stansted early this morning I'm currently at Oslo
Gardermoen airport waiting for my connecting flight to Hovdebygda. I am
annoyed that the terrorists have won and that I have to suffer the
stigma that flying has turned into. Not being able to take a plastic
bottle of water through the security check is simply disgraceful.

Don't get me wrong---I'm sympathetic to concerns about the ability to
smuggle liquid explosives using food containers. But why is it that as
soon as I'm /through/ the security check I can still buy all the
ingredients for a Molotov Cocktail? Not to mention glass bottles that
can be broken and used to make a primitive knife (just wrap one end of
an elongated shard in a scarf or belt you bought at one of the many
clothes pushers).

The retailers are laughing all the way to the bank of course. They are
in a stronger position than ever before to sell their goods. After the
strict enforcement of a single piece of (smaller) hand-luggage per
person everyone that comes through the security check is guaranteed to
have at least one hand free to carry their waiting lounge shopping.

It seems to me that the new security restrictions is a lot of hassle for
very little actual gain. If I was a more conspiratorial person I might
suggest that is was just scare-mongering---it has worked well in the
past to cover up or downplay other issues. It's probably just as well
that my lack of political wherewithal makes me completely unable to
think of what could be worth covering up. (Oh, /wait!/ Did you see how
well that just worked?)

*A couple hours later:* Adding insult to injury, I was just told at the
security check that I could not take the two half-litre bottles of
Cognac that I bought at the Stansted tax-free through. Apparently the
plastic bag was supposed to be sealed; the bottles still being unopened
and me showing the receipt fazed them /not at all/.

On advice from the airline's customer service desk I ended up stuffing
the bottles in my laptop bag and checking that in as a separate item of
hold luggage (after first taking my laptop out---I'm not /crazy/). Now
let's hope the bottles don't break.

*Two hours hence:* Well, crap. This really isn't my day. It has now
transpired that my plane is more than two and a half hours delayed. Of
course, my spare battery and charger is still in the laptop bag that I
checked in earlier.

#  LocalWords:  Stansted Gardermoen
