#+title: Connected!
#+date: <2006-04-30>

We finally have a network connection at the new place. Though we don't
have ADSL yet (there's a problem transferring it here because [[http://plus.net][plus]]'s
website thinks my flat is a business address) [[http://plus.net][plus]] kindly gives us a
backup phone connection. We tried to get it working yesterday but got
no dial tone and figured the phone was not working yet (it was only
connected on Thursday, and there was talks about a fault on the line
somewhere). It still didn't work today but after unpacking a phone and
successfully making a call to my mobile we smelled a rat, and, indeed,
we had a dead socket. Plugging the modem into the master socket we
could call out /just fine/.

Only problem is the cable is very short and the master socket is in
the hallway. Luckily there's a small closet just across for it with
room for a seat. It'll be great to have ADSL again though. Here's
[[http://www.flickr.com/photos/skugg/137138509/][Nadia]] enjoying our current connection arrangement.

#  LocalWords:  ADSL
