#+title: How I record Guitar
#+date: <2020-12-11>
#+category: Music

In my musical journey I try to record myself occasionally to track my
progress, and be able to critically listen to myself so I can fix my
mistakes. This is brief note on how I normally do that.

I plug the guitar into a Yamaha THR-10 amp, which has an USB output.
By installing the [[https://uk.yamaha.com/en/products/musical_instruments/guitars_basses/amps_accessories/thr/downloads.html][Yamaha Steinberg USB Driver]], I can connect the THR10
to my computer and use it as an input interface for Garageband.

The THR-10 exposes 4 input channels:

- *Channel 1 & 2*: left/right with effects
- *Channel 3 & 4*: left/right /without/ effects

I record clean. Using both channels 3 & 4 gives a sort of "synthetic"
stereo. I think. It sounds pretty good, anyway! Recording clean means
I can change the amp later; adding or removing distortion, delay,
reverb or chorus; say. (Also I haven't been able to disable the guitar
amp effects in Garageband, so recording the clean input from the amp is
the only way to avoid stacking the amp's and GarageBand's effects for
a /truly shit/ sound.)


* Abstract                                                         :noexport:

In my musical journey I try to record myself occasionally to track my
progress, and be able to critically listen to myself so I can fix my
mistakes. This is brief note on how I normally do that.

#  LocalWords:  THR Steinberg Garageband GarageBand's
