#+title: In-sewer Ants
#+date: <2006-08-12>

I remember laughing very hard at a comic-book joke as a kid. A red
indian with horrific injuries goes to visit his witch-doctor:

#+BEGIN_VERSE
--- What brought this on?
--- I was out hunting when an eagle attacked me, but luckily it dropped me in front of a flock of runaway buffalo!
--- Luckily?
--- Yes, it's the only thing my medical insurance covers!
#+END_VERSE

I used to find it hilarious back then, but having now started looking
into insurance I realise that the joke's on me, and I don't find it so
funny anymore. Here's an excerpt from the exclusion clause in Abbey's
accident cover:

#+BEGIN_QUOTE
  We will not pay benefits for an accident that is directly or
  indirectly the result of:

  -  war, invasion, acts of foreign enemies, civil war, rebellion, or
     being on naval, military or air force duty, service or operations;
  -  riding a motorcycle or moped as a driver or passenger;
  -  scuba-diving, rock climbing or mountaineering of any type,
     potholing or parachuting;
  -  competing in any race other than on foot or whilst swimming;
  -  exposure to exceptional danger (except in an attempt to save human
     life);
  -  the manufacture or use of explosives;
  -  flying except as a fare paying passenger;
  -  your suicide, your own illegal acts, your intentional
     self-inflicted injury, whether you are sane or insane;
  -  being under the influence of or being affected by alcohol or drugs
     unless under the advice of a doctor for a condition other than
     alcohol or drug addiction;
  -  radiation or contamination or the effects of radiation;
  -  HIV, AIDS or any related condition or disease
  -  you having any sickness, disease, naturally occurring condition,
     injury or degenerative process.
#+END_QUOTE

If the poor red indian in the joke above had had this insurance, I'm
pretty sure the cretins would have managed to weasel their way out of
paying for his claim.

#  LocalWords:  indian
