#+title: What I want for my Birthday
#+date: <2006-04-03>

According to the [[https://www.worldlandtrust.org][World Land Trust]], citing [[https://www.independent.co.uk/][The Independent]], Britons
last year spent £3.6 billion on food, healthcare and accessories for
their pets. I realise that pets have to eat and that the occasional
visit to the vet is in order, but a shocking £294 million alone was
spent on /pet gifts/.

I am saddened and distraught by this mindless waste; to put it in
perspective, £294 million could save /20 million acres/ of Rain forest.
That's more than a third of what is cut down for timber, agriculture
and development each year; 1.5 acres a second, according to [[http://www.rain-tree.com/facts.htm][this site]];
just shy of 50 million acres.

If you were thinking of buying me a present for my birthday (hint
hint, it's the 24th of April) then I suggest you [[https://www.worldlandtrust.org/appeals/buy-an-acre/][save an acre of Rain
forest]]. It's +only £25, so buy someone else one too. And maybe one
for yourself+ £100.
